name: StandaloneExample
options:
  bundleIdPrefix: com.example
  deploymentTarget:
    iOS: 16.0
  xcodeVersion: 16.0

packages:
  # 将 Key 改为与仓库名一致，提高识别率
  iOS_SDK:
    url: https://github.com/greathousesh/iOS_SDK.git
    from: 0.0.16

targets:
  StandaloneExample:
    type: application
    platform: iOS
    deploymentTarget: 16.0
    sources:
      - path: Sources
    dependencies:
      - package: iOS_SDK
        product: MySDK # 明确指定 Package 中的 Product
    settings:
      PRODUCT_BUNDLE_IDENTIFIER: com.example.StandaloneExample
    info:
      path: Sources/Info.plist
      properties:
        CFBundleIdentifier: $(PRODUCT_BUNDLE_IDENTIFIER)
        CFBundleShortVersionString: 1.0.0
        CFBundleVersion: 1
        UILaunchScreen: {}
